# k8s/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  namespace: default # Or your target namespace
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app-container
        image: 811492260998.dkr.ecr.ap-southeast-1.amazonaws.com/bndz/backend:latest
        ports:
        - containerPort: 8000